# Generated by Django 2.2.4 on 2020-12-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_app', '0002_showtime_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
