# Generated by Django 2.2.4 on 2020-12-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_app', '0003_auto_20201214_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
